name: NodeJs CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
#         cache: 'npm'
#         cache-dependency-path: |
#           package-lock.json
    - name: Cache
      uses: actions/cache@v2.1.8
      with:
    # A list of files, directories, and wildcard patterns to cache and restore
        path: package-lock.json
    # An explicit key for restoring and saving the cache
        key: mynewkey
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    
    - run: npm install
    
#     - run: npm test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: package-lock.json 
        # The desired behavior if no files are found using the provided path.
